---

- name: Install unattended upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable and start unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
