---

- name: Set options in /boot/config.txt
  ansible.builtin.blockinfile:
    path: /boot/config.txt
    insertafter: EOF
    block: "{{ lookup('ansible.builtin.template', pi_boot_config_template) }}"
  notify: Reboot system

- name: Add cgroup directives to /boot/cmdline.txt
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
