---

- name: Set options in /boot/config.txt
  ansible.builtin.blockinfile:
    path: /boot/config.txt
    insertafter: EOF
    block: "{{ lookup('ansible.builtin.template', pi_boot_config_template) }}"
  notify: Reboot system

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
