---

- name: Set options in boot configuration
  ansible.builtin.blockinfile:
    path: "{{ pi_boot_config_path }}"
    insertafter: EOF
    block: "{{ lookup('ansible.builtin.template', pi_boot_config_template) }}"
  notify: Reboot system

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
