---

- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configure fail2ban
  ansible.builtin.template:
    src: "{{ pi_fail2ban_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
