---

- name: Configure locale
  ansible.general.locale_gen:
    name: "{{ pi_locale }}"
    state: present

- name: Configure timezone
  ansible.general.timezone:
    name: "{{ pi_timezone }}"

- name: Configure keyboard
  ansible.builtin.template:
    src: keyboard.j2
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: '0644'
