---

- name: Configure sshd
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    validate: "sshd -t -f %s"
  loop: "{{ pi_sshd_config }}"
  notify: Reload sshd
  state: present
  validate: 'sshd -t -f %s'
