name: Ansible Lint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
